/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Bista;
import Consecionariocon.Controlador;
import Modelo.Crud;
/**
 *
 * @author EQUIPO
 */
public class Vista extends javax.swing.JFrame {
    Controlador tr=new Controlador(this);
    public Vista() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cod = new javax.swing.JTextField();
        nom = new javax.swing.JTextField();
        ap = new javax.swing.JTextField();
        cor = new javax.swing.JTextField();
        guardarc = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(cod, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 150, 30));
        getContentPane().add(nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 150, 40));
        getContentPane().add(ap, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 150, 30));
        getContentPane().add(cor, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 150, 40));

        guardarc.setText("Guardar");
        guardarc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarcActionPerformed(evt);
            }
        });
        getContentPane().add(guardarc, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 380, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\EQUIPO\\Documents\\NetBeansProjects\\Interfaz\\src\\interfaz\\600x600bf-60.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guardarcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarcActionPerformed
        tr.control();
    }//GEN-LAST:event_guardarcActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField ap;
    public javax.swing.JTextField cod;
    public javax.swing.JTextField cor;
    private javax.swing.JButton guardarc;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JTextField nom;
    // End of variables declaration//GEN-END:variables

}

